import type { Metadata } from "next";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import { regionProfiles } from "@/lib/regions";
import { ESTIMATE_INQUIRY_URL } from "@/lib/external-links";
const SITE_URL=(process.env.NEXT_PUBLIC_SITE_URL||"https://olbarun.kr").replace(/\/$/,"");
const title="전국 지역별 이사 정보 | 시·도·시군구 이사업체 비교";const description="서울·경기·인천·부산·대구 등 전국 17개 시·도와 시·군·구별 이사 특징, 손없는날, 날씨와 지역별 비교견적 정보를 확인하세요.";
export const metadata:Metadata={title,description,alternates:{canonical:`${SITE_URL}/moving`},openGraph:{title,description,url:`${SITE_URL}/moving`,type:"website",siteName:"올바른이사",locale:"ko_KR"}};
export default function MovingHub(){const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"홈",item:SITE_URL},{"@type":"ListItem",position:2,name:"전국 지역별 이사",item:`${SITE_URL}/moving`}]};return <><SiteHeader/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/><main><section className="sub-hero"><div className="wrap narrow"><div className="breadcrumb"><a href="/">홈</a><span>›</span><strong>지역별 이사</strong></div><span className="eyebrow">전국 지역별 이사</span><h1>먼저 시·도를 선택하고<br/>우리 지역 조건을 확인하세요.</h1><p>아파트 밀집지역, 구도심, 산업단지, 관광지, 외곽 생활권은 차량 접근과 작업시간이 서로 다릅니다. 전국 → 시·도 → 시·군·구 순서로 확인하면 원하는 지역을 더 빠르게 찾을 수 있습니다.</p></div></section><section className="section white"><div className="wrap"><div className="province-jump-grid">{regionProfiles.map(region=><a className="province-jump-card" href={`/moving/${region.slug}`} key={region.slug}><strong>{region.name}</strong><span>{region.districts.length}개 지역</span><p>{region.summary}</p><b>{region.name} 전체 보기 →</b></a>)}</div></div></section><section className="section"><div className="wrap"><span className="eyebrow">빠른 지역 선택</span><h2 className="section-title">시·군·구에서 바로 찾기</h2><p className="section-desc">자주 찾는 지역을 바로 선택하거나, 각 시·도 허브에서 전체 지역을 확인할 수 있습니다.</p><div className="all-region-grid">{regionProfiles.map(region=><article className="home-region-card" key={region.slug}><div className="home-region-head"><a href={`/moving/${region.slug}`}><strong>{region.name}</strong></a><span>{region.districts.length}개 지역</span></div><div className="home-district-links">{region.districts.slice(0,6).map(d=><a key={d} href={`/moving/${region.slug}/${encodeURIComponent(d)}`}>{d}</a>)}</div><a className="region-main-link" href={`/moving/${region.slug}`}>{region.name} 전체 지역 보기 →</a></article>)}</div></div></section><section className="section white"><div className="wrap"><div className="cta"><div><h2>출발지와 도착지가 정해졌나요?</h2><p>지역과 날짜, 현장조건을 정리한 뒤 외부 비교견적 신청 페이지에서 문의하세요.</p></div><a href={ESTIMATE_INQUIRY_URL}>무료 비교견적 시작</a></div></div></section></main><SiteFooter/></>}
