import type { Metadata } from "next";
import { notFound } from "next/navigation";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import { movingServices,type MovingServiceSlug } from "@/lib/service-content";
import { ESTIMATE_INQUIRY_URL } from "@/lib/external-links";
type Props={params:Promise<{slug:string}>};
const SITE_URL=(process.env.NEXT_PUBLIC_SITE_URL||"https://olbarun.kr").replace(/\/$/,"");
export function generateStaticParams(){return Object.keys(movingServices).map(slug=>({slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params;const data=movingServices[slug as MovingServiceSlug];if(!data)return{};const title=`${data.name} 비교견적 | 비용·체크사항`;const description=`${data.name}을 준비할 때 확인할 작업범위, 차량과 인원, 추가비 기준과 지역별 견적 비교 방법을 정리했습니다.`;const url=`${SITE_URL}/service/${slug}`;return{title,description,alternates:{canonical:url},openGraph:{title,description,url,type:"website",siteName:"올바른이사",locale:"ko_KR"}}}
export default async function ServicePage({params}:Props){const{slug}=await params;const data=movingServices[slug as MovingServiceSlug];if(!data)notFound();return <div className="service-page"><SiteHeader compact/><main><section className="sub-hero service-hero"><div className="wrap service-hero-grid"><div><span className="eyebrow">이사 유형 가이드</span><h1>{data.name},<br/>가격보다 포함 범위를 먼저 보세요.</h1><p>{data.lead}</p><div className="hero-actions"><a className="primary-link" href={ESTIMATE_INQUIRY_URL}>{data.name} 비교견적 받기</a><a className="secondary-link" href="/moving">지역별 이사 보기</a></div></div><div className="service-summary-card"><span>추천 상황</span><strong>{data.name}</strong><p>{data.fit}</p></div></div></section><section className="section white"><div className="wrap"><span className="eyebrow">비교 기준</span><h2 className="section-title">{data.name} 견적에서 꼭 확인할 5가지</h2><div className="service-check-grid">{data.points.map((p,i)=><article className="service-check-card" key={p}><span>{String(i+1).padStart(2,"0")}</span><strong>{p}</strong><p>견적서에 포함 여부와 추가비 조건을 구분해서 확인하세요.</p></article>)}</div></div></section><section className="section"><div className="wrap two-col-info"><div><span className="eyebrow">현장 조건</span><h2 className="section-title">같은 {data.name}도 집과 건물에 따라 달라집니다</h2><p>층수, 엘리베이터, 사다리차 설치 가능 여부, 이사차량 주차 위치, 현관까지의 운반거리가 달라지면 필요한 인원과 작업시간도 달라집니다. 방문견적이나 사진견적 때 출발지와 도착지 조건을 모두 알려주는 것이 좋습니다.</p><ul className="check-list"><li>출발지와 도착지 층수</li><li>엘리베이터 사용 가능 여부와 예약시간</li><li>이사차량 정차 위치</li><li>대형가전·가구 분해조립 여부</li><li>장거리·주말·손없는날 일정</li></ul></div><div className="highlight-card"><strong>지역까지 함께 비교하세요</strong><p>같은 이사 유형이라도 지역의 도로·주차·아파트 관리규정에 따라 조건이 달라집니다.</p><a href="/moving">전국 지역별 이사 정보 →</a></div></div></section><section className="section white"><div className="wrap"><div className="cta"><div><h2>{data.name}을 준비하고 계신가요?</h2><p>지역, 날짜, 작업조건을 정리한 뒤 외부 비교견적 신청 페이지에서 문의해보세요.</p></div><a href={ESTIMATE_INQUIRY_URL}>무료 비교견적 시작</a></div></div></section></main><SiteFooter/></div>}
