import MovingCalendar from "@/components/MovingCalendar";
import { regionProfiles } from "@/lib/regions";

const services=[
  ["📦","포장이사","포장부터 운반·정리까지 한 번에 비교","packing-moving"],
  ["🏠","원룸이사","소형 이사에 맞는 차량·도움 범위 비교","studio-moving"],
  ["🚚","일반이사","직접 포장하고 운송 중심으로 비교","general-moving"],
  ["🏢","사무실이사","건물 반입·업무 공백까지 고려한 비교","office-moving"],
];

export default function Home(){return <>
<header className="site-header"><div className="wrap header-inner"><a href="/" className="brand">올바른이사</a><nav className="nav" aria-label="주요 메뉴"><a href="#service">이사 종류</a><a href="#calendar">손없는날·날씨</a><a href="#region">지역별 이사</a><a href="/estimate">비교견적</a></nav></div></header>
<main>
<section className="hero home-hero"><div className="wrap hero-grid"><div><span className="eyebrow">전국 이사 비교·생활정보</span><h1>이사 비용만 보지 말고,<br/>날짜와 지역 조건까지 비교하세요.</h1><p>올바른이사는 포장이사·원룸이사·일반이사·사무실이사를 지역별 특성과 함께 비교하고, 손없는날·날씨·전입신고·전기·도시가스 같은 실제 이사 준비 정보까지 한곳에 정리합니다.</p><div className="hero-actions"><a className="primary-link" href="/estimate">무료 비교견적 받기</a><a className="secondary-link" href="#region">내 지역 이사 정보 보기</a></div><div className="trust-strip"><span>전국 시·군·구 정보</span><span>지역별 생활권 분석</span><span>손없는날·날씨 확인</span></div></div><div className="estimate-box"><span className="mini-label">빠른 비교 시작</span><h2>이사 조건부터 정리하세요</h2><p className="small">지역과 날짜, 이사 유형, 작업조건을 입력하면 비교할 항목이 더 명확해집니다.</p><div className="quick-points"><span>✓ 출발·도착 지역</span><span>✓ 포장·원룸·일반·사무실</span><span>✓ 사다리차·엘리베이터·대형가전</span><span>✓ 날짜와 손없는날 확인</span></div><a className="primary-btn button-link" href="/estimate">비교견적 시작하기</a></div></div></section>
<section className="section white" id="service"><div className="wrap"><span className="eyebrow">이사 유형</span><h2 className="section-title">어떤 이사를 준비하시나요?</h2><p className="section-desc">같은 거리라도 포장 범위와 작업인원에 따라 견적 구조가 달라집니다. 먼저 유형별 차이를 확인하세요.</p><div className="service-grid">{services.map(([icon,title,desc,slug])=><a href={`/service/${slug}`} className="card service-card-link" key={title}><div className="service-icon">{icon}</div><strong>{title}</strong><p>{desc}</p><span className="card-more">비교 기준 보기 →</span></a>)}</div></div></section>
<section className="section home-info-band"><div className="wrap"><div className="home-info-grid"><div><span className="eyebrow">이사 전에 많이 묻는 것</span><h2 className="section-title">견적보다 먼저 확인하면 좋은 3가지</h2></div><div className="home-info-items"><article><strong>추가금</strong><p>주차거리, 층수, 짐 증가와 대형가전 작업 조건을 미리 확인하세요.</p></article><article><strong>이사 날짜</strong><p>주말·월말·손없는날은 수요가 몰릴 수 있어 여러 날짜를 같이 비교하세요.</p></article><article><strong>건물 규정</strong><p>엘리베이터 예약, 보양비, 차량 진입시간은 관리사무소마다 다를 수 있습니다.</p></article></div></div></div></section>
<section className="section white" id="calendar"><div className="wrap"><span className="eyebrow">날짜 선택</span><h2 className="section-title">손없는날과 날씨를 같이 보세요</h2><p className="section-desc">좋은 날짜라도 비·강풍·한파가 겹치면 작업이 어려울 수 있습니다. 실제 이사 전에는 최신 예보를 다시 확인하세요.</p><MovingCalendar/></div></section>
<section className="section" id="region"><div className="wrap"><span className="eyebrow">전국 지역별 이사</span><h2 className="section-title">내 지역의 이사 조건부터 확인하세요</h2><p className="section-desc">전국 17개 시·도와 시·군·구별로 주거 형태, 차량 접근, 교통과 생활권 특성을 다르게 정리했습니다.</p><div className="all-region-grid">{regionProfiles.map(r=><article className="home-region-card" key={r.slug}><div className="home-region-head"><strong>{r.name}</strong><span>{r.districts.length}개 지역</span></div><p>{r.summary}</p><div className="home-district-links">{r.districts.slice(0,4).map(d=><a key={d} href={`/moving/${r.slug}/${encodeURIComponent(d)}`}>{d}</a>)}</div><a className="region-main-link" href={`/moving/${r.slug}/${encodeURIComponent(r.districts[0])}`}>{r.name} 지역 이사 보기 →</a></article>)}</div></div></section>
<section className="section white"><div className="wrap"><span className="eyebrow">이사 준비 순서</span><h2 className="section-title">복잡한 이사 준비를 네 단계로</h2><div className="steps-grid home-steps"><div className="card"><strong>01. 지역·날짜 확인</strong><p>출발지와 도착지의 주차·엘리베이터 조건, 손없는날과 날씨를 먼저 확인합니다.</p></div><div className="card"><strong>02. 이사 유형 선택</strong><p>포장이사, 원룸이사, 일반이사, 사무실이사 중 필요한 작업범위를 정합니다.</p></div><div className="card"><strong>03. 견적 조건 비교</strong><p>차량, 인원, 사다리차, 운반거리와 추가비 기준을 같은 조건으로 비교합니다.</p></div><div className="card"><strong>04. 행정·생활 이전</strong><p>전입신고와 등기 확인, 전기·도시가스·인터넷 등 생활서비스 이전을 준비합니다.</p></div></div></div></section>
<section className="section"><div className="wrap"><div className="cta"><div><h2>이사 날짜나 지역이 정해졌나요?</h2><p>조건을 입력하고 업체별 견적에서 무엇이 포함되는지 비교해보세요.</p></div><a href="/estimate">무료 비교견적 시작</a></div></div></section>
</main><footer className="footer"><div className="wrap"><strong>올바른이사</strong><p>전국 지역별 이사 조건과 생활정보, 비교견적을 연결하는 이사 준비 플랫폼입니다.</p><p>※ 실제 견적과 서비스 조건은 업체, 날짜, 현장 상황에 따라 달라질 수 있습니다.</p></div></footer></>}
