import type { Metadata } from "next";
import { notFound } from "next/navigation";
import MovingCalendar from "@/components/MovingCalendar";
import { getDistrictRegion, regionProfiles } from "@/lib/regions";
import { getDistrictGuide } from "@/lib/district-content";
import { getGyeonggiGuide } from "@/lib/gyeonggi-content";
import { getIncheonGuide } from "@/lib/incheon-content";
import { getBusanGuide } from "@/lib/busan-content";
import { getDaeguGuide } from "@/lib/daegu-content";
import { getDaejeonGuide } from "@/lib/daejeon-content";
import { getGwangjuGuide } from "@/lib/gwangju-content";
import { getUlsanGuide } from "@/lib/ulsan-content";
import { getRemainingRegionGuide } from "@/lib/remaining-regions-content";
import { getRegionHeroImage } from "@/lib/region-assets";
import { getRegionFaq } from "@/lib/region-faq";

type Props = { params: Promise<{ sido: string; sigungu: string }> };
export async function generateStaticParams(){return regionProfiles.flatMap(r=>r.districts.map(d=>({sido:r.slug,sigungu:d})))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {sido,sigungu}=await params;const data=getDistrictRegion(sido,sigungu);if(!data)return{};const {region,district}=data;const base=(process.env.NEXT_PUBLIC_SITE_URL||"https://example.com").replace(/\/$/,"");return{title:`${district} 이사업체 비교견적 | 손없는날·날씨·이사 준비 | 올바른이사`,description:`${region.name} ${district}의 생활권별 이사 특징과 차량 접근, 손없는날, 지역 날씨, 전입신고, 등기부, 전기·도시가스 이전 정보를 확인하세요.`,alternates:{canonical:`${base}/moving/${encodeURIComponent(sido)}/${encodeURIComponent(district)}`}}}
export default async function DistrictPage({params}:Props){const {sido,sigungu}=await params;const data=getDistrictRegion(sido,sigungu);if(!data)notFound();const {region,district}=data;const special=region.name==="경기"?getGyeonggiGuide(district):region.name==="인천"?getIncheonGuide(district):region.name==="부산"?getBusanGuide(district):region.name==="대구"?getDaeguGuide(district):region.name==="대전"?getDaejeonGuide(district):region.name==="광주"?getGwangjuGuide(district):region.name==="울산"?getUlsanGuide(district):getRemainingRegionGuide(region.name,district);const local=special??getDistrictGuide(region.name,district);const heroImage=getRegionHeroImage(sido,district);const faqs=getRegionFaq(region.name,district);const factors=Array.from(new Set((local.neighborhoods??[]).flatMap(i=>i.tags??[]))).slice(0,8);const base=(process.env.NEXT_PUBLIC_SITE_URL||"https://example.com").replace(/\/$/,"");const pageUrl=`${base}/moving/${encodeURIComponent(sido)}/${encodeURIComponent(district)}`;const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"홈",item:base},{"@type":"ListItem",position:2,name:`${region.name} 이사`,item:`${base}/#region`},{"@type":"ListItem",position:3,name:`${district} 이사`,item:pageUrl}]};const faqLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};return <div className="region-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqLd)}}/><header className="site-header"><div className="wrap header-inner"><a href="/" className="brand">올바른이사</a><nav className="nav"><a href="/estimate">비교견적</a><a href="#local-calendar">손없는날·날씨</a><a href="/#region">지역별 이사</a></nav></div></header><main>
<section className="sub-hero region-hero"><div className="wrap region-hero-grid"><div className="region-hero-copy"><div className="breadcrumb"><a href="/">홈</a><span>›</span><span>{region.name}</span><span>›</span><strong>{district}</strong></div><span className="eyebrow">{region.name} 지역별 이사</span><h1>{district} 이사업체,<br/>가격보다 조건부터 비교하세요.</h1><p>{local.localIntro}</p><div className="hero-actions"><a className="primary-link" href={`/estimate?region=${encodeURIComponent(region.name)}&district=${encodeURIComponent(district)}`}>{district} 무료 비교견적</a><a className="secondary-link" href="#local-calendar">{district} 손없는날·날씨</a></div></div><div className="region-hero-media">{heroImage?<img src={heroImage} alt={`${region.name} ${district} 이사 지역 이미지`}/>:<div className="region-image-placeholder"><strong>{district} 대표 이미지 영역</strong><span>lib/region-assets.ts에 이미지 URL을 입력하세요.</span></div>}</div></div></section>
<section className="section white"><div className="wrap"><span className="eyebrow">지역 현장 정보</span><h2 className="section-title">{district} 이사에서 먼저 볼 조건</h2><p className="section-desc">{region.summary}</p><div className="tips-grid region-tips"><div className="card"><strong>주거 형태</strong><p>{region.housing}</p></div><div className="card"><strong>차량 접근</strong><p>{region.access}</p></div><div className="card"><strong>이동 시간</strong><p>{region.traffic}</p></div></div><div className="local-note"><strong>{district} 현장 체크</strong><ul className="check-list">{local.localChecklist.map(x=><li key={x}>{x}</li>)}</ul></div></div></section>
{local.neighborhoods?.length?<section className="section local-area-section"><div className="wrap"><div className="local-area-head"><div><span className="eyebrow">생활권별 차이</span><h2 className="section-title">{district} 안에서도 이사 조건이 달라집니다</h2><p className="section-desc">실제 이사에서는 아파트 밀집지, 구도심, 산업·관광 생활권마다 차량 진입과 작업시간이 달라집니다.</p></div><div className="factor-pills">{factors.map(x=><span key={x}>{x}</span>)}</div></div><div className="neighborhood-grid">{local.neighborhoods.map((x,i)=><article className="neighborhood-card" key={x.name}><span>{String(i+1).padStart(2,"0")}</span><strong>{x.name}</strong><p>{x.note}</p><div className="factor-pills">{x.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></div></section>:null}
<section className="section region-calendar-section" id="local-calendar"><div className="wrap"><span className="eyebrow">이사 날짜 선택</span><h2 className="section-title">{district} 손없는날과 지역 날씨</h2><p className="section-desc">날짜만 고르기보다 강수확률과 기온, 지역 교통 특성을 함께 확인하면 실제 이사 준비에 도움이 됩니다.</p><MovingCalendar regionName={region.name} districtName={district} lockRegion/><div className="region-source-note"><strong>안내:</strong> 손없는날은 전통적 음력 기준 참고 정보이며 날씨는 단기예보입니다. 이사 직전 최신 예보를 다시 확인하세요.</div></div></section>
<section className="section white"><div className="wrap two-col-info"><div><span className="eyebrow">견적 비교 포인트</span><h2 className="section-title">{district} 포장이사에서 꼭 확인할 항목</h2><p>{local.movingNote}</p><ul className="check-list"><li>작업 인원과 차량 톤수</li><li>사다리차·엘리베이터 비용</li><li>차량 정차지에서 현관까지 운반거리</li><li>대형가구·가전 분해조립 범위</li><li>장거리·도서·외곽 추가비 기준</li></ul></div><div className="highlight-card"><strong>{district} 이사 팁</strong><p>{region.tip}</p><a href="/estimate">조건 입력하고 비교견적 받기 →</a></div></div></section>
<section className="section"><div className="wrap"><span className="eyebrow">이사 후 행정</span><h2 className="section-title">{district} 전입신고 준비</h2><p className="section-desc">온라인은 정부24, 방문은 새 주소지 관할 주민센터에서 진행할 수 있습니다. 임차인은 확정일자와 권리관계도 함께 확인하세요.</p><div className="guide-grid"><article className="guide-card"><span className="guide-step">01</span><strong>전입신고</strong><p>전입 후 14일 이내 신고가 원칙이며 세대관계에 따른 필요서류를 확인하세요.</p></article><article className="guide-card"><span className="guide-step">02</span><strong>확정일자</strong><p>임차인은 보증금 보호를 위해 전입·점유와 함께 확정일자 등 요건을 확인하세요.</p></article><article className="guide-card"><span className="guide-step">03</span><strong>주소 확인</strong><p>계약서 주소와 실제 동·호수, 등기사항증명서의 표시가 일치하는지 확인하세요.</p></article></div><div className="official-links"><a href="https://www.gov.kr" target="_blank" rel="noreferrer">정부24 확인하기 ↗</a></div></div></section>
<section className="section white"><div className="wrap"><span className="eyebrow">등기부 확인</span><h2 className="section-title">계약 전 등기사항증명서 확인</h2><div className="guide-grid"><article className="guide-card"><span className="guide-step">갑구</span><strong>소유자·압류 확인</strong><p>계약 상대방과 소유자가 같은지, 압류·가압류 등이 있는지 봅니다.</p></article><article className="guide-card"><span className="guide-step">을구</span><strong>담보권 확인</strong><p>근저당권·전세권 등 선순위 권리와 채권최고액을 확인합니다.</p></article><article className="guide-card"><span className="guide-step">주소</span><strong>계약 대상 일치</strong><p>실제 계약할 집과 발급한 등기사항증명서가 같은 물건인지 확인합니다.</p></article></div><div className="official-links"><a href="https://www.iros.go.kr" target="_blank" rel="noreferrer">대한민국 법원 인터넷등기소 ↗</a></div></div></section>
<section className="section utility-section"><div className="wrap"><span className="eyebrow">이삿날 생활요금</span><h2 className="section-title">전기·도시가스 이전</h2><div className="utility-grid"><article className="utility-card"><div className="utility-number">123</div><strong>한국전력 고객센터</strong><p>전기 이사정산과 관련 상담은 국번 없이 123에서 확인할 수 있습니다. 공동주택은 관리사무소 정산 여부도 확인하세요.</p><a href="https://home.kepco.co.kr" target="_blank" rel="noreferrer">한전 확인하기 ↗</a></article><article className="utility-card"><div className="utility-number small-number">주소별 확인</div><strong>{district} 도시가스</strong><p>공급회사가 주소에 따라 다르므로 전출 정산·철거·연결 예약은 관할 고객센터를 확인하세요.</p><a href="https://www.citygas.or.kr/company/find/index.jsp" target="_blank" rel="noreferrer">도시가스 고객센터 찾기 ↗</a></article></div></div></section>
<section className="section white"><div className="wrap"><h2 className="section-title">{district} 이사 종류별 비교</h2><div className="service-grid"><div className="card"><strong>포장이사</strong><p>포장·운반·정리와 추가서비스 포함범위를 비교하세요.</p></div><div className="card"><strong>원룸이사</strong><p>짐 양, 차량 크기, 계단·엘리베이터와 기사 도움범위를 확인하세요.</p></div><div className="card"><strong>일반이사</strong><p>직접 포장할 경우 차량과 운반인력 범위를 명확히 하세요.</p></div><div className="card"><strong>사무실이사</strong><p>{local.officeNote}</p></div></div></div></section>
<section className="section region-faq-section"><div className="wrap"><span className="eyebrow">자주 묻는 질문</span><h2 className="section-title">{district} 이사 준비 FAQ</h2><div className="region-faq-list">{faqs.map((f,i)=><details className="region-faq-item" key={f.question} open={i===0}><summary><span>Q</span>{f.question}</summary><div className="region-faq-answer"><span>A</span><p>{f.answer}</p></div></details>)}</div></div></section>
<section className="section white"><div className="wrap"><div className="cta"><div><h2>{district} 이사를 준비하고 계신가요?</h2><p>지역과 날짜, 작업조건을 입력해 견적을 비교해보세요.</p></div><a href={`/estimate?region=${encodeURIComponent(region.name)}&district=${encodeURIComponent(district)}`}>무료 비교견적 시작</a></div></div></section>
</main><footer className="footer"><div className="wrap"><strong>올바른이사</strong><p>{region.name} {district}의 이사 준비 정보와 비교견적 안내 페이지입니다.</p></div></footer></div>}
