import type { Metadata } from "next";
import { notFound } from "next/navigation";
import MovingCalendar from "@/components/MovingCalendar";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import RegionHeroImage from "@/components/RegionHeroImage";
import { getDistrictRegion, regionProfiles } from "@/lib/regions";
import { getDistrictGuide } from "@/lib/district-content";
import { getSmartRegionFallback } from "@/lib/smart-region-fallback";
import { getGyeonggiGuide } from "@/lib/gyeonggi-content";
import { getIncheonGuide } from "@/lib/incheon-content";
import { getBusanGuide } from "@/lib/busan-content";
import { getDaeguGuide } from "@/lib/daegu-content";
import { getDaejeonGuide } from "@/lib/daejeon-content";
import { getGwangjuGuide } from "@/lib/gwangju-content";
import { getUlsanGuide } from "@/lib/ulsan-content";
import { getRemainingRegionGuide } from "@/lib/remaining-regions-content";
import { getRegionalOverride } from "@/lib/regional-overrides";
import { getRegionalMeta,getRegionalHeroDescription,getNearbyDistricts,movingTimeline } from "@/lib/moving-page-tools";
import { getRegionHeroImage,getRegionHeroVideo } from "@/lib/region-assets";
import { getRegionFaq } from "@/lib/region-faq";
import { ESTIMATE_INQUIRY_URL } from "@/lib/external-links";
type Props={params:Promise<{sido:string;sigungu:string}>};
const SITE_URL=(process.env.NEXT_PUBLIC_SITE_URL||"https://olbarun.kr").replace(/\/$/,"");
export async function generateStaticParams(){return regionProfiles.flatMap(r=>r.districts.map(d=>({sido:r.slug,sigungu:d})))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const{sido,sigungu}=await params;const data=getDistrictRegion(sido,sigungu);if(!data)return{};const{region,district}=data;const meta=getRegionalMeta(region.name,district);const url=`${SITE_URL}/moving/${encodeURIComponent(sido)}/${encodeURIComponent(district)}`;return{...meta,alternates:{canonical:url},openGraph:{title:meta.title,description:meta.description,type:"website",url}}}
export default async function DistrictPage({params}:Props){const{sido,sigungu}=await params;const data=getDistrictRegion(sido,sigungu);if(!data)notFound();const{region,district}=data;const researched=getRegionalOverride(region.name,district);const special=researched??(region.name==="경기"?getGyeonggiGuide(district):region.name==="인천"?getIncheonGuide(district):region.name==="부산"?getBusanGuide(district):region.name==="대구"?getDaeguGuide(district):region.name==="대전"?getDaejeonGuide(district):region.name==="광주"?getGwangjuGuide(district):region.name==="울산"?getUlsanGuide(district):getRemainingRegionGuide(region.name,district));const local=special??(region.name==="서울"?getDistrictGuide(region.name,district):getSmartRegionFallback(region.name,district));const heroDescription=getRegionalHeroDescription(region.name,district);const heroImage=getRegionHeroImage(sido,district);const heroVideo=getRegionHeroVideo(sido,district);const faqs=getRegionFaq(region.name,district);const nearby=getNearbyDistricts(sido,district);const factors=Array.from(new Set((local.neighborhoods??[]).flatMap(i=>i.tags??[]))).slice(0,8);const pageUrl=`${SITE_URL}/moving/${encodeURIComponent(sido)}/${encodeURIComponent(district)}`;const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"홈",item:SITE_URL},{"@type":"ListItem",position:2,name:"지역별 이사",item:`${SITE_URL}/moving`},{"@type":"ListItem",position:3,name:region.name,item:`${SITE_URL}/moving/${sido}`},{"@type":"ListItem",position:4,name:`${district} 이사`,item:pageUrl}]};const faqLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};return <div className="region-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqLd)}}/><SiteHeader/><main>
<section className="sub-hero region-hero"><div className="wrap region-hero-grid"><div className="region-hero-copy"><div className="breadcrumb"><a href="/">홈</a><span>›</span><a href="/moving">지역별 이사</a><span>›</span><a href={`/moving/${sido}`}>{region.name}</a><span>›</span><strong>{district}</strong></div><span className="eyebrow">{region.name} 지역별 이사</span><h1>{district} 이사업체,<br/>가격보다 조건부터 비교하세요.</h1><p>{heroDescription}</p><div className="hero-actions"><a className="primary-link" href={ESTIMATE_INQUIRY_URL}>{district} 무료 비교견적</a><a className="secondary-link" href="#local-calendar">{district} 손없는날·날씨</a></div></div><div className="region-hero-media"><RegionHeroImage src={heroImage} videoSrc={heroVideo} region={region.name} district={district}/></div></div></section>
<section className="section white"><div className="wrap"><span className="eyebrow">지역 현장 정보</span><h2 className="section-title">{district} 이사에서 먼저 볼 조건</h2><p className="section-desc">{region.summary}</p><div className="tips-grid region-tips"><div className="card"><strong>주거 형태</strong><p>{region.housing}</p></div><div className="card"><strong>차량 접근</strong><p>{region.access}</p></div><div className="card"><strong>이동 시간</strong><p>{region.traffic}</p></div></div><div className="local-note"><strong>{district} 현장 체크</strong><ul className="check-list">{local.localChecklist.map(x=><li key={x}>{x}</li>)}</ul></div></div></section>
{local.neighborhoods?.length?<section className="section local-area-section"><div className="wrap"><div className="local-area-head"><div><span className="eyebrow">생활권별 차이</span><h2 className="section-title">{district} 안에서도 이사 조건이 달라집니다</h2><p className="section-desc">같은 시·군·구 안에서도 아파트 밀집지, 구도심, 산업·관광 생활권에 따라 차량 진입과 작업시간이 달라질 수 있습니다.</p></div><div className="factor-pills">{factors.map(x=><span key={x}>{x}</span>)}</div></div><div className="neighborhood-grid">{local.neighborhoods.map((x,i)=><article className="neighborhood-card" key={x.name}><span>{String(i+1).padStart(2,"0")}</span><strong>{x.name}</strong><p>{x.note}</p><div className="factor-pills">{x.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></div></section>:null}
<section className="section region-calendar-section" id="local-calendar"><div className="wrap"><span className="eyebrow">이사 날짜 선택</span><h2 className="section-title">{district} 손없는날과 지역 날씨</h2><p className="section-desc">날짜만 고르기보다 강수확률과 기온, 지역 교통 특성을 함께 확인하면 실제 이사 준비에 도움이 됩니다.</p><MovingCalendar regionName={region.name} districtName={district} lockRegion/><div className="region-source-note"><strong>안내:</strong> 손없는날은 전통적 음력 기준 참고 정보이며 날씨는 단기예보입니다. 이사 직전 최신 예보를 다시 확인하세요.</div></div></section>
<section className="section white"><div className="wrap two-col-info"><div><span className="eyebrow">견적 비교 포인트</span><h2 className="section-title">{district} 포장이사에서 꼭 확인할 항목</h2><p>{local.movingNote}</p><ul className="check-list"><li>작업 인원과 차량 톤수</li><li>사다리차·엘리베이터 비용</li><li>차량 정차지에서 현관까지 운반거리</li><li>대형가구·가전 분해조립 범위</li><li>장거리·도서·외곽 추가비 기준</li></ul></div><div className="highlight-card"><strong>{district} 이사 팁</strong><p>{region.tip}</p><a href={ESTIMATE_INQUIRY_URL}>비교견적 문의하기 →</a></div></div></section>
<section className="section moving-timeline-section" id="moving-timeline"><div className="wrap"><span className="eyebrow">날짜별 준비</span><h2 className="section-title">{district} 이사 체크리스트</h2><p className="section-desc">한꺼번에 준비하면 빠뜨리기 쉽습니다. 이사 한 달 전부터 이사 다음 날까지 해야 할 일을 순서대로 확인하세요.</p><div className="moving-timeline">{movingTimeline.map(step=><article className="timeline-card" key={step.day}><div className="timeline-day">{step.day}</div><div><strong>{step.title}</strong><ul>{step.items.map(x=><li key={x}>{x}</li>)}</ul></div></article>)}</div><div className="official-links"><a href="/guide/moving-checklist">전체 이사 체크리스트 보기 →</a></div></div></section>
<section className="section white"><div className="wrap"><span className="eyebrow">공통 이사 절차</span><h2 className="section-title">지역 정보와 공통 행정절차는 나눠서 확인하세요</h2><p className="section-desc">지역마다 달라지는 것은 주거환경과 차량 접근, 교통조건입니다. 전입신고·등기 확인·생활요금 이전처럼 전국 공통 절차는 별도 가이드에서 자세히 확인할 수 있습니다.</p><div className="guide-grid"><a className="guide-card" href="/guide/address-change"><span className="guide-step">행정</span><strong>전입신고·확정일자</strong><p>이사 후 주소 이전과 임차인이 함께 확인할 기본 절차를 정리했습니다.</p></a><a className="guide-card" href="/guide/registry"><span className="guide-step">계약</span><strong>등기사항증명서 확인</strong><p>소유자와 권리관계를 어떤 순서로 보면 되는지 확인하세요.</p></a><a className="guide-card" href="/guide/utilities"><span className="guide-step">생활</span><strong>전기·도시가스 이전</strong><p>출발지 정산과 도착지 연결을 준비하는 기본 순서를 확인하세요.</p></a></div></div></section>
<section className="section"><div className="wrap"><span className="eyebrow">이사 유형</span><h2 className="section-title">{district} 이사 종류별 비교</h2><div className="service-grid"><a className="card" href="/service/packing-moving"><strong>포장이사</strong><p>포장·운반·정리와 추가서비스 포함범위를 비교하세요.</p></a><a className="card" href="/service/studio-moving"><strong>원룸이사</strong><p>짐 양, 차량 크기, 계단·엘리베이터와 기사 도움범위를 확인하세요.</p></a><a className="card" href="/service/general-moving"><strong>일반이사</strong><p>직접 포장할 경우 차량과 운반인력 범위를 명확히 하세요.</p></a><a className="card" href="/service/office-moving"><strong>사무실이사</strong><p>{local.officeNote}</p></a></div></div></section>
{nearby.length>0?<section className="section white nearby-section"><div className="wrap"><span className="eyebrow">주변 지역</span><h2 className="section-title">{district}와 함께 보는 {region.name} 이사 지역</h2><p className="section-desc">출발지와 도착지가 다른 시·군·구라면 양쪽 지역의 차량 접근과 이사 조건을 함께 확인하세요.</p><div className="nearby-links">{nearby.map(n=><a key={n} href={`/moving/${sido}/${encodeURIComponent(n)}`}>{n} 이사 정보 <span>→</span></a>)}</div></div></section>:null}
<section className="section region-faq-section"><div className="wrap"><span className="eyebrow">자주 묻는 질문</span><h2 className="section-title">{district} 이사 준비 FAQ</h2><div className="region-faq-list">{faqs.map((f,i)=><details className="region-faq-item" key={f.question} open={i===0}><summary><span>Q</span>{f.question}</summary><div className="region-faq-answer"><span>A</span><p>{f.answer}</p></div></details>)}</div></div></section>
<section className="section white"><div className="wrap"><div className="cta"><div><h2>{district} 이사를 준비하고 계신가요?</h2><p>지역과 날짜, 작업조건을 정리한 뒤 외부 비교견적 신청 페이지에서 문의해보세요.</p></div><a href={ESTIMATE_INQUIRY_URL}>무료 비교견적 시작</a></div></div></section>
</main><SiteFooter/></div>}
